language: cpp
compiler:
  - clang
os:
  - linux

addons:
  apt:
    packages:
      - g++
      - cmake
      - libboost-dev
      - curl

jobs:
  include:
    - name: "checks"
      script:
        - mkdir _build
        - cd _build
        - cmake .. && make && ./crawler --help

notifications:
  email: false